# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ICRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('end_user', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('site_address', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_no', models.IntegerField(verbose_name=10)),
                ('req_date_of_installation_by_customer', models.DateTimeField(verbose_name='Req Date Installation of Customer')),
                ('pre_sign_off_sheet_status', models.CharField(max_length=255)),
                ('site_status', models.CharField(max_length=255)),
                ('no_of_jobs', models.IntegerField(verbose_name=5)),
                ('name_of_product_supplied', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(verbose_name=5)),
                ('transformer_valve_size_details', models.CharField(max_length=255)),
                ('material_reached_at_site', models.CharField(max_length=255)),
                ('sales_manager_request_no', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Today')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(max_length=255)),
                ('issue_reported', models.CharField(max_length=255)),
                ('visit_required', models.CharField(max_length=255)),
                ('customer_req_date', models.DateTimeField(verbose_name='Customer Req Date')),
            ],
        ),
        migrations.CreateModel(
            name='ScopeSupply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helium_cylinder', models.CharField(max_length=255)),
                ('calibration_gas_cylinder', models.CharField(max_length=255)),
                ('ss_tubing', models.CharField(max_length=255)),
                ('ss_tubing_size', models.CharField(max_length=255)),
                ('standard_length_ss_tube', models.CharField(max_length=255)),
                ('tubing_accessories', models.CharField(max_length=255)),
                ('flanges', models.CharField(max_length=255)),
                ('communication_mode', models.CharField(max_length=255)),
                ('icrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ICRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('end_user', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('site_address', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_no', models.IntegerField(verbose_name=10)),
                ('req_date_of_installation_by_customer', models.DateTimeField(verbose_name='Req Date Installation of Customer')),
                ('pre_sign_off_sheet_status', models.CharField(max_length=255)),
                ('site_status', models.CharField(max_length=255)),
                ('no_of_jobs', models.IntegerField(verbose_name=5)),
                ('name_of_product_supplied', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(verbose_name=5)),
                ('transformer_valve_size_details', models.CharField(max_length=255)),
                ('material_reached_at_site', models.CharField(max_length=255)),
                ('sales_manager_request_no', models.CharField(max_length=255)),
                ('date', models.DateTimeField(verbose_name='Today')),
            ],
        ),
        migrations.AddField(
            model_name='productmodel',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ServiceCall'),
        ),
    ]
